package minime

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"net/textproto"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

type recordingGenerator struct {
	bootstrapCalled          bool
	generateCandidatesCalled bool
	generateStatesCalled     bool
}

type failingGenerator struct {
	candidateError error
	stateError     error
}

type blockingGenerator struct {
	started chan struct{}
	release chan struct{}
}

type timeoutGenerator struct{}

func (g *recordingGenerator) Bootstrap(_ context.Context, _ GenerationEnvironment, session *sessionRecord) error {
	g.bootstrapCalled = true
	session.Status = "custom-bootstrap"
	session.CurrentStepLabel = "Custom bootstrap"
	session.Notes = "Bootstrapped by injected generator."
	return nil
}

func (g *recordingGenerator) GenerateCandidates(_ context.Context, _ GenerationEnvironment, session *sessionRecord, _ string) error {
	g.generateCandidatesCalled = true
	session.Status = "custom-candidates"
	session.CurrentStepLabel = "Custom candidates"
	session.Notes = "Candidates generated by injected generator."
	return nil
}

func (g *recordingGenerator) GenerateStates(_ context.Context, _ GenerationEnvironment, session *sessionRecord, states []string, _ string, _ map[string]string) error {
	g.generateStatesCalled = true
	session.Status = "custom-states"
	session.CurrentStepLabel = strings.Join(states, ",")
	session.Notes = "States generated by injected generator."
	return nil
}

func (g *failingGenerator) Bootstrap(_ context.Context, _ GenerationEnvironment, _ *sessionRecord) error {
	return nil
}

func (g *failingGenerator) GenerateCandidates(_ context.Context, _ GenerationEnvironment, _ *sessionRecord, _ string) error {
	return g.candidateError
}

func (g *failingGenerator) GenerateStates(_ context.Context, _ GenerationEnvironment, _ *sessionRecord, _ []string, _ string, _ map[string]string) error {
	return g.stateError
}

func (g *blockingGenerator) Bootstrap(_ context.Context, _ GenerationEnvironment, _ *sessionRecord) error {
	return nil
}

func (g *blockingGenerator) GenerateCandidates(_ context.Context, _ GenerationEnvironment, session *sessionRecord, _ string) error {
	close(g.started)
	<-g.release
	session.Status = "custom-candidates"
	session.CurrentStepLabel = "Released candidate generation"
	session.Notes = "Candidates generated after release."
	return nil
}

func (g *blockingGenerator) GenerateStates(_ context.Context, _ GenerationEnvironment, _ *sessionRecord, _ []string, _ string, _ map[string]string) error {
	return nil
}

func (timeoutGenerator) Bootstrap(_ context.Context, _ GenerationEnvironment, _ *sessionRecord) error {
	return nil
}

func (timeoutGenerator) GenerateCandidates(_ context.Context, _ GenerationEnvironment, _ *sessionRecord, _ string) error {
	return nil
}

func (timeoutGenerator) GenerateStates(ctx context.Context, _ GenerationEnvironment, _ *sessionRecord, _ []string, _ string, _ map[string]string) error {
	<-ctx.Done()
	return ctx.Err()
}

func TestCreateSessionPersistsToDisk(t *testing.T) {
	t.Parallel()

	server := newTestServer(t)
	recorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	if recorder.Code != http.StatusCreated {
		t.Fatalf("expected status %d, got %d: %s", http.StatusCreated, recorder.Code, recorder.Body.String())
	}

	var snapshot remoteSessionSnapshot
	decodeJSON(t, recorder, &snapshot)
	if snapshot.SessionID == "" {
		t.Fatal("expected session_id to be present")
	}
	if snapshot.Status != "created" {
		t.Fatalf("expected created status, got %q", snapshot.Status)
	}

	storeData, err := os.ReadFile(filepath.Join(server.config.DataRoot, "store.json"))
	if err != nil {
		t.Fatalf("read store file: %v", err)
	}
	if !strings.Contains(string(storeData), snapshot.SessionID) {
		t.Fatalf("expected store file to contain session id %q", snapshot.SessionID)
	}
}

func TestNewServerUsesScriptGeneratorMode(t *testing.T) {
	t.Parallel()

	server, err := NewServer(Config{
		Port:                 "0",
		DataRoot:             t.TempDir(),
		DeviceTokens:         []string{"test-token"},
		GeneratorMode:        "script",
		RepoRoot:             "/tmp/repo-root",
		PythonExecutable:     "/usr/bin/python3",
		ImageGeneratorScript: "/tmp/generate.py",
		StatePipelineScript:  "/tmp/state.py",
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	generator, ok := server.generator.(ScriptGenerator)
	if !ok {
		t.Fatalf("expected ScriptGenerator, got %T", server.generator)
	}
	if generator.RepoRoot != "/tmp/repo-root" {
		t.Fatalf("expected repo root to be forwarded, got %q", generator.RepoRoot)
	}
	if generator.ImageGeneratorScript != "/tmp/generate.py" {
		t.Fatalf("expected image generator script to be forwarded, got %q", generator.ImageGeneratorScript)
	}
	if generator.StatePipelineScript != "/tmp/state.py" {
		t.Fatalf("expected state pipeline script to be forwarded, got %q", generator.StatePipelineScript)
	}
}

func TestNewServerRejectsUnknownGeneratorMode(t *testing.T) {
	t.Parallel()

	_, err := NewServer(Config{
		Port:          "0",
		DataRoot:      t.TempDir(),
		DeviceTokens:  []string{"test-token"},
		GeneratorMode: "mystery",
	})
	if err == nil {
		t.Fatal("expected invalid generator mode to fail")
	}
	if !strings.Contains(err.Error(), `unsupported generator mode "mystery"`) {
		t.Fatalf("expected unsupported generator mode error, got %v", err)
	}
}

func TestLoadConfigParsesWorkerCount(t *testing.T) {
	t.Setenv("MINIME_WORKER_COUNT", "4")

	config := LoadConfig()
	if config.WorkerCount != 4 {
		t.Fatalf("expected worker count 4, got %d", config.WorkerCount)
	}
}

func TestLoadConfigFallsBackToSingleWorkerForInvalidValues(t *testing.T) {
	t.Setenv("MINIME_WORKER_COUNT", "0")

	config := LoadConfig()
	if config.WorkerCount != 1 {
		t.Fatalf("expected worker count 1 for invalid input, got %d", config.WorkerCount)
	}
}

func TestLoadConfigCanDisableEmbeddedWorkers(t *testing.T) {
	t.Setenv("MINIME_RUN_WORKERS", "false")

	config := LoadConfig()
	if config.RunWorkers {
		t.Fatal("expected embedded workers to be disabled")
	}
}

func TestBootstrapCreatesJobAndExposesJobEndpoint(t *testing.T) {
	t.Parallel()

	server := newTestServer(t)
	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	bootstrapRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/bootstrap", `{}`)
	if bootstrapRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, bootstrapRecorder.Code, bootstrapRecorder.Body.String())
	}

	jobID := bootstrapRecorder.Header().Get("X-MiniMe-Job-ID")
	if jobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header")
	}

	var snapshot remoteSessionSnapshot
	decodeJSON(t, bootstrapRecorder, &snapshot)
	if snapshot.LastJobID != jobID {
		t.Fatalf("expected last_job_id %q, got %q", jobID, snapshot.LastJobID)
	}

	jobRecorder := performRequest(t, server.Handler(), http.MethodGet, "/v1/minime/jobs/"+jobID, "")
	if jobRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, jobRecorder.Code, jobRecorder.Body.String())
	}

	var job remoteJobSnapshot
	decodeJSON(t, jobRecorder, &job)
	if job.Type != "bootstrap" {
		t.Fatalf("expected bootstrap job type, got %q", job.Type)
	}
	if job.Status != "completed" {
		t.Fatalf("expected completed job status, got %q", job.Status)
	}
}

func TestWorkerServerProcessesQueuedJobsFromSeparateApiServer(t *testing.T) {
	t.Parallel()

	dataRoot := t.TempDir()
	apiServer, err := NewServer(Config{
		Port:               "0",
		DataRoot:           dataRoot,
		DeviceTokens:       []string{"test-token"},
		RunWorkers:         false,
		WorkerPollInterval: 10 * time.Millisecond,
	})
	if err != nil {
		t.Fatalf("create api server: %v", err)
	}

	createRecorder := performRequest(t, apiServer.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	uploadRecorder := uploadSourcePhoto(t, apiServer, created.SessionID, "source.png", minimalPNG, "image/png")
	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	candidateRecorder := performRequest(t, apiServer.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/candidates:generate", `{}`)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}
	jobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if jobID == "" {
		t.Fatal("expected candidate generation job id")
	}
	if job := waitForJobStatus(t, apiServer, jobID, "queued"); job.Status != "queued" {
		t.Fatalf("expected queued job, got %q", job.Status)
	}

	workerServer, err := NewServer(Config{
		Port:               "0",
		DataRoot:           dataRoot,
		DeviceTokens:       []string{"test-token"},
		RunWorkers:         true,
		WorkerPollInterval: 10 * time.Millisecond,
	})
	if err != nil {
		t.Fatalf("create worker server: %v", err)
	}

	if job := waitForJobTerminal(t, workerServer, jobID); job.Status != "completed" {
		t.Fatalf("expected completed worker job, got %q", job.Status)
	}

	session := fetchSessionSnapshot(t, apiServer, created.SessionID)
	if session.Status != "candidate-generated" {
		t.Fatalf("expected candidate-generated session status, got %q", session.Status)
	}
	if len(session.Candidates) == 0 {
		t.Fatal("expected candidates to be visible through api server after worker completion")
	}
}

func TestServerReloadsPersistedSessionsAndJobs(t *testing.T) {
	t.Parallel()

	dataRoot := t.TempDir()
	config := Config{
		Port:         "0",
		DataRoot:     dataRoot,
		DeviceTokens: []string{"test-token"},
	}

	server, err := NewServer(config)
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	bootstrapRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/bootstrap", `{}`)
	var bootstrapped remoteSessionSnapshot
	decodeJSON(t, bootstrapRecorder, &bootstrapped)

	reloaded, err := NewServer(config)
	if err != nil {
		t.Fatalf("reload server: %v", err)
	}

	sessionRecorder := performRequest(t, reloaded.Handler(), http.MethodGet, "/v1/minime/sessions/"+created.SessionID, "")
	if sessionRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, sessionRecorder.Code, sessionRecorder.Body.String())
	}

	var reloadedSession remoteSessionSnapshot
	decodeJSON(t, sessionRecorder, &reloadedSession)
	if reloadedSession.Status != "workspace-bootstrapped" {
		t.Fatalf("expected workspace-bootstrapped, got %q", reloadedSession.Status)
	}
	if reloadedSession.LastJobID != bootstrapped.LastJobID {
		t.Fatalf("expected last_job_id %q, got %q", bootstrapped.LastJobID, reloadedSession.LastJobID)
	}

	jobRecorder := performRequest(t, reloaded.Handler(), http.MethodGet, "/v1/minime/jobs/"+bootstrapped.LastJobID, "")
	if jobRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, jobRecorder.Code, jobRecorder.Body.String())
	}
}

func TestUploadGenerateCandidatesAndDownloadAsset(t *testing.T) {
	t.Parallel()

	server := newTestServer(t)
	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, err := writer.CreateFormFile("photos", "portrait.png")
	if err != nil {
		t.Fatalf("create multipart file: %v", err)
	}
	if _, err := part.Write(minimalPNG); err != nil {
		t.Fatalf("write multipart file: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)

	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	var uploaded remoteSessionSnapshot
	decodeJSON(t, uploadRecorder, &uploaded)
	if len(uploaded.SourcePhotos) != 1 {
		t.Fatalf("expected 1 source photo, got %d", len(uploaded.SourcePhotos))
	}

	candidateRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/candidates:generate", `{}`)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}

	candidateJobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if candidateJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for candidate generation")
	}
	job := waitForJobTerminal(t, server, candidateJobID)
	if job.Status != "completed" {
		t.Fatalf("expected completed candidate job, got %q", job.Status)
	}

	var candidates remoteSessionSnapshot
	candidates = fetchSessionSnapshot(t, server, created.SessionID)
	if len(candidates.Candidates) == 0 {
		t.Fatal("expected generated candidates")
	}
	if candidates.Candidates[0].DownloadURL == "" {
		t.Fatal("expected candidate download URL")
	}

	downloadPath := strings.TrimPrefix(candidates.Candidates[0].DownloadURL, "http://example.com")
	downloadRecorder := performRequest(t, server.Handler(), http.MethodGet, downloadPath, "")
	if downloadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, downloadRecorder.Code, downloadRecorder.Body.String())
	}
	if contentType := downloadRecorder.Header().Get("Content-Type"); contentType == "" {
		t.Fatal("expected content-type for downloaded asset")
	}
	if !bytes.Equal(downloadRecorder.Body.Bytes(), minimalPNG) {
		t.Fatal("expected downloaded asset bytes to match uploaded placeholder content")
	}
}

func TestUploadRejectsUnsupportedContentType(t *testing.T) {
	t.Parallel()

	server := newTestServer(t)
	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	partHeader := textproto.MIMEHeader{}
	partHeader.Set("Content-Disposition", `form-data; name="photos"; filename="notes.txt"`)
	partHeader.Set("Content-Type", "text/plain")
	part, err := writer.CreatePart(partHeader)
	if err != nil {
		t.Fatalf("create multipart part: %v", err)
	}
	if _, err := part.Write([]byte("not an image")); err != nil {
		t.Fatalf("write multipart part: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)

	if uploadRecorder.Code != http.StatusBadRequest {
		t.Fatalf("expected status %d, got %d: %s", http.StatusBadRequest, uploadRecorder.Code, uploadRecorder.Body.String())
	}
	if !strings.Contains(uploadRecorder.Body.String(), "unsupported uploaded photo content type") {
		t.Fatalf("expected unsupported content type error, got %s", uploadRecorder.Body.String())
	}
}

func TestUploadRejectsOversizedPhoto(t *testing.T) {
	t.Parallel()

	server := newTestServer(t)
	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	partHeader := textproto.MIMEHeader{}
	partHeader.Set("Content-Disposition", `form-data; name="photos"; filename="huge.png"`)
	partHeader.Set("Content-Type", "image/png")
	part, err := writer.CreatePart(partHeader)
	if err != nil {
		t.Fatalf("create multipart part: %v", err)
	}
	oversized := bytes.Repeat([]byte("a"), int(maxUploadPhotoSizeBytes)+1)
	if _, err := part.Write(oversized); err != nil {
		t.Fatalf("write multipart part: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)

	if uploadRecorder.Code != http.StatusBadRequest {
		t.Fatalf("expected status %d, got %d: %s", http.StatusBadRequest, uploadRecorder.Code, uploadRecorder.Body.String())
	}
	if !strings.Contains(uploadRecorder.Body.String(), "uploaded photo exceeds 20 MB limit") {
		t.Fatalf("expected oversized upload error, got %s", uploadRecorder.Body.String())
	}
}

func TestServerUsesInjectedGenerator(t *testing.T) {
	t.Parallel()

	generator := &recordingGenerator{}
	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     t.TempDir(),
		DeviceTokens: []string{"test-token"},
		Generator:    generator,
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	bootstrapRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/bootstrap", `{}`)
	if bootstrapRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, bootstrapRecorder.Code, bootstrapRecorder.Body.String())
	}
	if !generator.bootstrapCalled {
		t.Fatal("expected injected generator bootstrap to be called")
	}

	var bootstrapped remoteSessionSnapshot
	decodeJSON(t, bootstrapRecorder, &bootstrapped)
	if bootstrapped.Status != "custom-bootstrap" {
		t.Fatalf("expected custom-bootstrap status, got %q", bootstrapped.Status)
	}
	if bootstrapped.Notes != "Bootstrapped by injected generator." {
		t.Fatalf("expected injected generator notes, got %q", bootstrapped.Notes)
	}
}

func TestActiveGenerationRejectsConcurrentSessionMutations(t *testing.T) {
	t.Parallel()

	generator := &blockingGenerator{
		started: make(chan struct{}),
		release: make(chan struct{}),
	}
	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     t.TempDir(),
		DeviceTokens: []string{"test-token"},
		Generator:    generator,
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	uploadRecorder := uploadSourcePhoto(t, server, created.SessionID, "source.png", minimalPNG, "image/png")
	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	candidateRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/candidates:generate", `{}`)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}
	candidateJobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if candidateJobID == "" {
		t.Fatal("expected queued candidate job header")
	}

	select {
	case <-generator.started:
	case <-time.After(2 * time.Second):
		t.Fatal("timed out waiting for candidate job to start")
	}
	waitForJobStatus(t, server, candidateJobID, "running")

	conflictUploadRecorder := uploadSourcePhoto(t, server, created.SessionID, "blocked.png", minimalPNG, "image/png")
	if conflictUploadRecorder.Code != http.StatusConflict {
		t.Fatalf("expected status %d, got %d: %s", http.StatusConflict, conflictUploadRecorder.Code, conflictUploadRecorder.Body.String())
	}
	if !strings.Contains(conflictUploadRecorder.Body.String(), activeGenerationError) {
		t.Fatalf("expected active-generation conflict, got %s", conflictUploadRecorder.Body.String())
	}

	conflictSelectionRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/candidate-selection",
		`{"selected_source_photo_id":"anything"}`,
	)
	if conflictSelectionRecorder.Code != http.StatusConflict {
		t.Fatalf("expected status %d, got %d: %s", http.StatusConflict, conflictSelectionRecorder.Code, conflictSelectionRecorder.Body.String())
	}

	close(generator.release)
	if job := waitForJobTerminal(t, server, candidateJobID); job.Status != "completed" {
		t.Fatalf("expected completed candidate job, got %q", job.Status)
	}
}

func TestGenerateStatesWithoutSelectedAssetReturnsBadRequest(t *testing.T) {
	t.Parallel()

	server := newTestServer(t)
	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	recorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/states:generate",
		`{"states":["idle-day"]}`,
	)
	if recorder.Code != http.StatusBadRequest {
		t.Fatalf("expected status %d, got %d: %s", http.StatusBadRequest, recorder.Code, recorder.Body.String())
	}
	if !strings.Contains(recorder.Body.String(), ErrNoSelectedAsset.Error()) {
		t.Fatalf("expected missing-selection error, got %s", recorder.Body.String())
	}

	var snapshot remoteSessionSnapshot
	sessionRecorder := performRequest(t, server.Handler(), http.MethodGet, "/v1/minime/sessions/"+created.SessionID, "")
	decodeJSON(t, sessionRecorder, &snapshot)
	if snapshot.LastJobID == "" {
		t.Fatal("expected failed state-generation job to be recorded")
	}

	jobRecorder := performRequest(t, server.Handler(), http.MethodGet, "/v1/minime/jobs/"+snapshot.LastJobID, "")
	if jobRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, jobRecorder.Code, jobRecorder.Body.String())
	}

	var job remoteJobSnapshot
	decodeJSON(t, jobRecorder, &job)
	if job.Status != "failed" {
		t.Fatalf("expected failed job status, got %q", job.Status)
	}
	if job.Error != ErrNoSelectedAsset.Error() {
		t.Fatalf("expected missing-selection job error, got %q", job.Error)
	}
}

func TestFailedCandidateGenerationPersistsJobAcrossReload(t *testing.T) {
	t.Parallel()

	dataRoot := t.TempDir()
	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     dataRoot,
		DeviceTokens: []string{"test-token"},
		Generator: &failingGenerator{
			candidateError: errors.New("candidate generation failed"),
		},
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, err := writer.CreateFormFile("photos", "portrait.png")
	if err != nil {
		t.Fatalf("create multipart file: %v", err)
	}
	if _, err := part.Write(minimalPNG); err != nil {
		t.Fatalf("write multipart file: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)
	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	candidateRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/candidates:generate", `{}`)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}
	candidateJobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if candidateJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for candidate generation")
	}
	job := waitForJobTerminal(t, server, candidateJobID)
	if job.Status != "failed" {
		t.Fatalf("expected failed candidate-generation job, got %q", job.Status)
	}

	session := fetchSessionSnapshot(t, server, created.SessionID)
	if session.LastJobID == "" {
		t.Fatal("expected failed candidate-generation job to be recorded")
	}

	reloaded, err := NewServer(Config{
		Port:         "0",
		DataRoot:     dataRoot,
		DeviceTokens: []string{"test-token"},
		Generator: &failingGenerator{
			candidateError: errors.New("candidate generation failed"),
		},
	})
	if err != nil {
		t.Fatalf("reload server: %v", err)
	}

	jobRecorder := performRequest(t, reloaded.Handler(), http.MethodGet, "/v1/minime/jobs/"+session.LastJobID, "")
	if jobRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, jobRecorder.Code, jobRecorder.Body.String())
	}

	var reloadedJob remoteJobSnapshot
	decodeJSON(t, jobRecorder, &reloadedJob)
	if reloadedJob.Status != "failed" {
		t.Fatalf("expected failed job status, got %q", reloadedJob.Status)
	}
	if reloadedJob.Error != "candidate generation failed" {
		t.Fatalf("expected persisted job error, got %q", reloadedJob.Error)
	}
}

func TestReloadMarksRunningJobsAsFailed(t *testing.T) {
	t.Parallel()

	dataRoot := t.TempDir()
	config := Config{
		Port:         "0",
		DataRoot:     dataRoot,
		DeviceTokens: []string{"test-token"},
	}

	server, err := NewServer(config)
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	server.mu.Lock()
	session := server.sessions[created.SessionID]
	job := server.createQueuedJobLocked(session, "generate-candidates", nil)
	job.Status = "running"
	session.Status = "generating-candidates"
	session.CurrentStepLabel = "Generating candidates"
	session.Notes = "Generating placeholder candidates from uploaded source photos."
	session.UpdatedAt = job.UpdatedAt
	if err := server.persistStoreLocked(); err != nil {
		server.mu.Unlock()
		t.Fatalf("persist running job: %v", err)
	}
	server.mu.Unlock()

	reloaded, err := NewServer(config)
	if err != nil {
		t.Fatalf("reload server: %v", err)
	}

	jobRecorder := performRequest(t, reloaded.Handler(), http.MethodGet, "/v1/minime/jobs/"+job.ID, "")
	if jobRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, jobRecorder.Code, jobRecorder.Body.String())
	}

	var recoveredJob remoteJobSnapshot
	decodeJSON(t, jobRecorder, &recoveredJob)
	if recoveredJob.Status != "failed" {
		t.Fatalf("expected failed recovered job status, got %q", recoveredJob.Status)
	}
	if recoveredJob.Error != interruptedJobError {
		t.Fatalf("expected interrupted job error, got %q", recoveredJob.Error)
	}

	sessionRecorder := performRequest(t, reloaded.Handler(), http.MethodGet, "/v1/minime/sessions/"+created.SessionID, "")
	if sessionRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, sessionRecorder.Code, sessionRecorder.Body.String())
	}

	var recoveredSession remoteSessionSnapshot
	decodeJSON(t, sessionRecorder, &recoveredSession)
	if recoveredSession.Status != "failed" {
		t.Fatalf("expected recovered session status failed, got %q", recoveredSession.Status)
	}
	if recoveredSession.Notes != interruptedJobError {
		t.Fatalf("expected recovered session note %q, got %q", interruptedJobError, recoveredSession.Notes)
	}
	if recoveredSession.LastJobID != job.ID {
		t.Fatalf("expected recovered last_job_id %q, got %q", job.ID, recoveredSession.LastJobID)
	}
}

func TestReloadRequeuesQueuedJobs(t *testing.T) {
	t.Parallel()

	dataRoot := t.TempDir()
	config := Config{
		Port:         "0",
		DataRoot:     dataRoot,
		DeviceTokens: []string{"test-token"},
	}

	server, err := NewServer(config)
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	server.mu.Lock()
	session := server.sessions[created.SessionID]
	sourceAsset, err := server.persistUploadedFileLocked(created.SessionID, "source-photos", "portrait.png", "image/png", bytes.NewReader(minimalPNG))
	if err != nil {
		server.mu.Unlock()
		t.Fatalf("persist source asset: %v", err)
	}
	session.SourcePhotos = append(session.SourcePhotos, sourceAsset)
	session.SelectedSourcePhotoID = sourceAsset.ID
	session.PublishedPreview = sourceAsset
	job := server.createQueuedJobLocked(session, "generate-candidates", nil)
	session.Status = "queued-candidates"
	session.CurrentStepLabel = "Queued candidate generation"
	session.Notes = "Candidate generation queued."
	session.UpdatedAt = job.UpdatedAt
	if err := server.persistStoreLocked(); err != nil {
		server.mu.Unlock()
		t.Fatalf("persist queued job: %v", err)
	}
	server.mu.Unlock()

	reloaded, err := NewServer(config)
	if err != nil {
		t.Fatalf("reload server: %v", err)
	}

	reloadedJob := waitForJobTerminal(t, reloaded, job.ID)
	if reloadedJob.Status != "completed" {
		t.Fatalf("expected completed reloaded job status, got %q (error=%q summary=%q)", reloadedJob.Status, reloadedJob.Error, reloadedJob.Summary)
	}

	reloadedSession := fetchSessionSnapshot(t, reloaded, created.SessionID)
	if reloadedSession.Status != "candidate-generated" {
		t.Fatalf("expected candidate-generated session status, got %q", reloadedSession.Status)
	}
	if len(reloadedSession.Candidates) != 1 {
		t.Fatalf("expected 1 generated candidate after requeue, got %d", len(reloadedSession.Candidates))
	}
}

func TestScriptGeneratorBootstrapCreatesWorkspaceFiles(t *testing.T) {
	t.Parallel()

	repoRoot := findRepoRoot(t)
	dataRoot := t.TempDir()
	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     dataRoot,
		DeviceTokens: []string{"test-token"},
		Generator: ScriptGenerator{
			RepoRoot: repoRoot,
		},
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	bootstrapRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/bootstrap", `{}`)
	if bootstrapRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, bootstrapRecorder.Code, bootstrapRecorder.Body.String())
	}

	workspaceRoot := filepath.Join(dataRoot, created.SessionID, "workspace")
	for _, relativePath := range []string{
		"manifest.json",
		"generation.log",
		"base-portrait-prompt.txt",
		"voxel-refine-prompt.txt",
	} {
		if _, err := os.Stat(filepath.Join(workspaceRoot, relativePath)); err != nil {
			t.Fatalf("expected workspace file %s: %v", relativePath, err)
		}
	}
}

func TestScriptGeneratorResolvesRepoRoot(t *testing.T) {
	t.Parallel()

	repoRoot := findRepoRoot(t)
	resolved, err := (ScriptGenerator{}).resolveRepoRoot()
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	if resolved != repoRoot {
		t.Fatalf("expected repo root %q, got %q", repoRoot, resolved)
	}
}

func TestScriptGeneratorGeneratesCandidatesViaScript(t *testing.T) {
	t.Parallel()

	repoRoot := findRepoRoot(t)
	dataRoot := t.TempDir()
	fakeGeneratorScript := writeFakeImageGeneratorScript(t)
	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     dataRoot,
		DeviceTokens: []string{"test-token"},
		Generator: ScriptGenerator{
			RepoRoot:             repoRoot,
			ImageGeneratorScript: fakeGeneratorScript,
		},
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, err := writer.CreateFormFile("photos", "portrait.png")
	if err != nil {
		t.Fatalf("create multipart file: %v", err)
	}
	if _, err := part.Write(minimalPNG); err != nil {
		t.Fatalf("write multipart file: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)
	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	candidateRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/candidates:generate", `{}`)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}
	candidateJobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if candidateJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for candidate generation")
	}
	candidateJob := waitForJobTerminal(t, server, candidateJobID)
	if candidateJob.Status != "completed" {
		t.Fatalf("expected completed candidate job, got %q", candidateJob.Status)
	}

	var snapshot remoteSessionSnapshot
	snapshot = fetchSessionSnapshot(t, server, created.SessionID)
	if snapshot.Status != "candidates-generated" {
		t.Fatalf("expected candidates-generated status, got %q", snapshot.Status)
	}
	if len(snapshot.Candidates) != 4 {
		t.Fatalf("expected 4 generated candidates, got %d", len(snapshot.Candidates))
	}
	if snapshot.SelectedCandidate == "" {
		t.Fatal("expected selected candidate after generation")
	}
	if snapshot.LastJobID == "" {
		t.Fatal("expected last job id after generation")
	}
}

func TestScriptGeneratorAppendsCandidatePromptSuffixAndCameraGuidance(t *testing.T) {
	t.Parallel()

	repoRoot := findRepoRoot(t)
	dataRoot := t.TempDir()
	fakeGeneratorScript := writeFakeImageGeneratorScript(t)
	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     dataRoot,
		DeviceTokens: []string{"test-token"},
		Generator: ScriptGenerator{
			RepoRoot:             repoRoot,
			ImageGeneratorScript: fakeGeneratorScript,
		},
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, err := writer.CreateFormFile("photos", "portrait.png")
	if err != nil {
		t.Fatalf("create multipart file: %v", err)
	}
	if _, err := part.Write(minimalPNG); err != nil {
		t.Fatalf("write multipart file: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)
	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	candidateRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/candidates:generate",
		`{"prompt_suffix":"Place the character naturally on a round pedestal."}`,
	)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}
	candidateJobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if candidateJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for candidate generation")
	}
	if job := waitForJobTerminal(t, server, candidateJobID); job.Status != "completed" {
		t.Fatalf("expected completed candidate job, got %q", job.Status)
	}

	promptPath := filepath.Join(
		dataRoot,
		created.SessionID,
		"workspace",
		"candidate-renders",
		"main-agent-candidate-01.png.prompt.txt",
	)
	promptData, err := os.ReadFile(promptPath)
	if err != nil {
		t.Fatalf("read generated prompt: %v", err)
	}
	prompt := string(promptData)
	if !strings.Contains(prompt, "facing straight toward the viewer with no horizontal turn") {
		t.Fatalf("expected updated camera guidance in prompt, got %q", prompt)
	}
	if !strings.Contains(prompt, "downward camera pitch of about five degrees") {
		t.Fatalf("expected five-degree downward camera guidance in prompt, got %q", prompt)
	}
	if !strings.Contains(prompt, "Place the character naturally on a round pedestal.") {
		t.Fatalf("expected candidate prompt suffix in prompt, got %q", prompt)
	}
}

func TestScriptGeneratorGeneratesStatesViaScript(t *testing.T) {
	t.Parallel()

	repoRoot := findRepoRoot(t)
	dataRoot := t.TempDir()
	fakeGeneratorScript := writeFakeImageGeneratorScript(t)
	fakeStatePipelineScript := writeFakeStatePipelineScript(t)
	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     dataRoot,
		DeviceTokens: []string{"test-token"},
		Generator: ScriptGenerator{
			RepoRoot:             repoRoot,
			ImageGeneratorScript: fakeGeneratorScript,
			StatePipelineScript:  fakeStatePipelineScript,
		},
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, err := writer.CreateFormFile("photos", "portrait.png")
	if err != nil {
		t.Fatalf("create multipart file: %v", err)
	}
	if _, err := part.Write(minimalPNG); err != nil {
		t.Fatalf("write multipart file: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)
	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	candidateRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/candidates:generate", `{}`)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}
	candidateJobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if candidateJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for candidate generation")
	}
	if job := waitForJobTerminal(t, server, candidateJobID); job.Status != "completed" {
		t.Fatalf("expected completed candidate job, got %q", job.Status)
	}

	statesRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/states:generate",
		`{"states":["idle-day","working"]}`,
	)
	if statesRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, statesRecorder.Code, statesRecorder.Body.String())
	}
	statesJobID := statesRecorder.Header().Get("X-MiniMe-Job-ID")
	if statesJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for state generation")
	}
	if job := waitForJobTerminal(t, server, statesJobID); job.Status != "completed" {
		t.Fatalf("expected completed state job, got %q", job.Status)
	}

	var snapshot remoteSessionSnapshot
	snapshot = fetchSessionSnapshot(t, server, created.SessionID)
	if snapshot.Status != "states-generated" {
		t.Fatalf("expected states-generated status, got %q", snapshot.Status)
	}
	if len(snapshot.StateAssets) != 2 {
		t.Fatalf("expected 2 generated states, got %d", len(snapshot.StateAssets))
	}
	for _, stateAsset := range snapshot.StateAssets {
		if stateAsset.SourceImage == nil || stateAsset.SourceImage.DownloadURL == "" {
			t.Fatalf("expected source image download URL for state %q", stateAsset.StateName)
		}
		if stateAsset.FinalAsset == nil || stateAsset.FinalAsset.DownloadURL == "" {
			t.Fatalf("expected final asset download URL for state %q", stateAsset.StateName)
		}

		sourceDownloadPath := strings.TrimPrefix(stateAsset.SourceImage.DownloadURL, "http://example.com")
		sourceDownloadRecorder := performRequest(t, server.Handler(), http.MethodGet, sourceDownloadPath, "")
		if sourceDownloadRecorder.Code != http.StatusOK {
			t.Fatalf("expected status %d for source image download, got %d: %s", http.StatusOK, sourceDownloadRecorder.Code, sourceDownloadRecorder.Body.String())
		}

		finalDownloadPath := strings.TrimPrefix(stateAsset.FinalAsset.DownloadURL, "http://example.com")
		finalDownloadRecorder := performRequest(t, server.Handler(), http.MethodGet, finalDownloadPath, "")
		if finalDownloadRecorder.Code != http.StatusOK {
			t.Fatalf("expected status %d for final asset download, got %d: %s", http.StatusOK, finalDownloadRecorder.Code, finalDownloadRecorder.Body.String())
		}
	}
}

func TestScriptGeneratorForwardsStatePromptSuffix(t *testing.T) {
	t.Parallel()

	repoRoot := findRepoRoot(t)
	dataRoot := t.TempDir()
	fakeGeneratorScript := writeFakeImageGeneratorScript(t)
	fakeStatePipelineScript := writeFakeStatePipelineScript(t)
	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     dataRoot,
		DeviceTokens: []string{"test-token"},
		Generator: ScriptGenerator{
			RepoRoot:             repoRoot,
			ImageGeneratorScript: fakeGeneratorScript,
			StatePipelineScript:  fakeStatePipelineScript,
		},
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, err := writer.CreateFormFile("photos", "portrait.png")
	if err != nil {
		t.Fatalf("create multipart file: %v", err)
	}
	if _, err := part.Write(minimalPNG); err != nil {
		t.Fatalf("write multipart file: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)
	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	candidateRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/candidates:generate", `{}`)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}
	candidateJobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if candidateJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for candidate generation")
	}
	if job := waitForJobTerminal(t, server, candidateJobID); job.Status != "completed" {
		t.Fatalf("expected completed candidate job, got %q", job.Status)
	}

	statesRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/states:generate",
		`{"states":["working"],"prompt_suffix":"Keep the pedestal contact shadow subtle."}`,
	)
	if statesRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, statesRecorder.Code, statesRecorder.Body.String())
	}
	statesJobID := statesRecorder.Header().Get("X-MiniMe-Job-ID")
	if statesJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for state generation")
	}
	if job := waitForJobTerminal(t, server, statesJobID); job.Status != "completed" {
		t.Fatalf("expected completed state job, got %q", job.Status)
	}

	suffixPath := filepath.Join(
		dataRoot,
		created.SessionID,
		"workspace",
		"state-renders",
		"main-agent",
		"working",
		"prompt_suffix.txt",
	)
	suffixData, err := os.ReadFile(suffixPath)
	if err != nil {
		t.Fatalf("read forwarded state prompt suffix: %v", err)
	}
	if strings.TrimSpace(string(suffixData)) != "Keep the pedestal contact shadow subtle." {
		t.Fatalf("expected forwarded state prompt suffix, got %q", string(suffixData))
	}
}

func TestSelectCandidateAndGenerateRequestedStates(t *testing.T) {
	t.Parallel()

	server := newTestServer(t)
	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	for _, name := range []string{"portrait-a.png", "portrait-b.png"} {
		part, err := writer.CreateFormFile("photos", name)
		if err != nil {
			t.Fatalf("create multipart file: %v", err)
		}
		if _, err := part.Write(minimalPNG); err != nil {
			t.Fatalf("write multipart file: %v", err)
		}
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)
	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	candidateRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/candidates:generate", `{}`)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}
	candidateJobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if candidateJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for candidate generation")
	}
	if job := waitForJobTerminal(t, server, candidateJobID); job.Status != "completed" {
		t.Fatalf("expected completed candidate job, got %q", job.Status)
	}

	var candidates remoteSessionSnapshot
	candidates = fetchSessionSnapshot(t, server, created.SessionID)
	if len(candidates.Candidates) != 2 {
		t.Fatalf("expected 2 generated candidates, got %d", len(candidates.Candidates))
	}

	selectionRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/candidate-selection",
		`{"selected_candidate_id":"`+candidates.Candidates[1].ID+`"}`,
	)
	if selectionRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, selectionRecorder.Code, selectionRecorder.Body.String())
	}

	var selected remoteSessionSnapshot
	decodeJSON(t, selectionRecorder, &selected)
	if selected.SelectedCandidate != candidates.Candidates[1].ID {
		t.Fatalf("expected selected candidate %q, got %q", candidates.Candidates[1].ID, selected.SelectedCandidate)
	}
	if selected.PublishedPreview == nil || selected.PublishedPreview.ID != candidates.Candidates[1].ID {
		t.Fatalf("expected published preview candidate %q", candidates.Candidates[1].ID)
	}
	if selectionJobID := selectionRecorder.Header().Get("X-MiniMe-Job-ID"); selectionJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for candidate selection")
	}

	statesRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/states:generate",
		`{"states":["idle","working"]}`,
	)
	if statesRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, statesRecorder.Code, statesRecorder.Body.String())
	}

	statesJobID := statesRecorder.Header().Get("X-MiniMe-Job-ID")
	if statesJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for state generation")
	}
	if job := waitForJobTerminal(t, server, statesJobID); job.Status != "completed" {
		t.Fatalf("expected completed state job, got %q", job.Status)
	}

	var generated remoteSessionSnapshot
	generated = fetchSessionSnapshot(t, server, created.SessionID)
	if generated.LastJobID != statesJobID {
		t.Fatalf("expected last_job_id %q, got %q", statesJobID, generated.LastJobID)
	}
	if generated.Status != "states-generated" {
		t.Fatalf("expected states-generated status, got %q", generated.Status)
	}
	if len(generated.StateAssets) != 2 {
		t.Fatalf("expected 2 generated state assets, got %d", len(generated.StateAssets))
	}
	if generated.StateAssets[0].StateName != "idle-day" {
		t.Fatalf("expected normalized first state idle-day, got %q", generated.StateAssets[0].StateName)
	}
	if generated.StateAssets[1].StateName != "working" {
		t.Fatalf("expected second state working, got %q", generated.StateAssets[1].StateName)
	}
	for _, stateAsset := range generated.StateAssets {
		if stateAsset.SourceImage == nil || stateAsset.SourceImage.DownloadURL == "" {
			t.Fatalf("expected source image download URL for state %q", stateAsset.StateName)
		}
		if stateAsset.FinalAsset == nil || stateAsset.FinalAsset.DownloadURL == "" {
			t.Fatalf("expected final asset download URL for state %q", stateAsset.StateName)
		}
	}

	jobRecorder := performRequest(t, server.Handler(), http.MethodGet, "/v1/minime/jobs/"+statesJobID, "")
	if jobRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, jobRecorder.Code, jobRecorder.Body.String())
	}

	var job remoteJobSnapshot
	decodeJSON(t, jobRecorder, &job)
	if job.Type != "generate-states" {
		t.Fatalf("expected generate-states job type, got %q", job.Type)
	}
	if job.Status != "completed" {
		t.Fatalf("expected completed job status, got %q", job.Status)
	}
	if job.Summary != "State generation complete." {
		t.Fatalf("expected state generation summary, got %q", job.Summary)
	}
}

func TestCandidateSelectionRejectsUnknownAssetIDs(t *testing.T) {
	t.Parallel()

	server := newTestServer(t)
	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	for _, name := range []string{"portrait-a.png", "portrait-b.png"} {
		part, err := writer.CreateFormFile("photos", name)
		if err != nil {
			t.Fatalf("create multipart file: %v", err)
		}
		if _, err := part.Write(minimalPNG); err != nil {
			t.Fatalf("write multipart file: %v", err)
		}
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)
	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	candidateRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/candidates:generate", `{}`)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}
	candidateJobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if candidateJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for candidate generation")
	}
	if job := waitForJobTerminal(t, server, candidateJobID); job.Status != "completed" {
		t.Fatalf("expected completed candidate job, got %q", job.Status)
	}

	unknownCandidateRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/candidate-selection",
		`{"selected_candidate_id":"candidate-missing"}`,
	)
	if unknownCandidateRecorder.Code != http.StatusBadRequest {
		t.Fatalf("expected status %d, got %d: %s", http.StatusBadRequest, unknownCandidateRecorder.Code, unknownCandidateRecorder.Body.String())
	}
	if !strings.Contains(unknownCandidateRecorder.Body.String(), "selected candidate was not found") {
		t.Fatalf("expected unknown candidate error, got %s", unknownCandidateRecorder.Body.String())
	}

	unknownSourceRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/candidate-selection",
		`{"selected_source_photo_id":"source-missing"}`,
	)
	if unknownSourceRecorder.Code != http.StatusBadRequest {
		t.Fatalf("expected status %d, got %d: %s", http.StatusBadRequest, unknownSourceRecorder.Code, unknownSourceRecorder.Body.String())
	}
	if !strings.Contains(unknownSourceRecorder.Body.String(), "selected source photo was not found") {
		t.Fatalf("expected unknown source error, got %s", unknownSourceRecorder.Body.String())
	}
}

func TestGenerateStatesRejectsUnknownStateNames(t *testing.T) {
	t.Parallel()

	server := newTestServer(t)
	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, err := writer.CreateFormFile("photos", "portrait-a.png")
	if err != nil {
		t.Fatalf("create multipart file: %v", err)
	}
	if _, err := part.Write(minimalPNG); err != nil {
		t.Fatalf("write multipart file: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	uploadRequest := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/photos", body)
	uploadRequest.Header.Set("Authorization", "Bearer test-token")
	uploadRequest.Header.Set("Content-Type", writer.FormDataContentType())
	uploadRecorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(uploadRecorder, uploadRequest)
	if uploadRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, uploadRecorder.Code, uploadRecorder.Body.String())
	}

	candidateRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions/"+created.SessionID+"/candidates:generate", `{}`)
	if candidateRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, candidateRecorder.Code, candidateRecorder.Body.String())
	}
	candidateJobID := candidateRecorder.Header().Get("X-MiniMe-Job-ID")
	if candidateJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for candidate generation")
	}
	if job := waitForJobTerminal(t, server, candidateJobID); job.Status != "completed" {
		t.Fatalf("expected completed candidate job, got %q", job.Status)
	}

	statesRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/states:generate",
		`{"states":["idle-day","dance-party"]}`,
	)
	if statesRecorder.Code != http.StatusBadRequest {
		t.Fatalf("expected status %d, got %d: %s", http.StatusBadRequest, statesRecorder.Code, statesRecorder.Body.String())
	}
	if !strings.Contains(statesRecorder.Body.String(), "unsupported state") || !strings.Contains(statesRecorder.Body.String(), "dance-party") {
		t.Fatalf("expected unsupported state error, got %s", statesRecorder.Body.String())
	}
}

func TestGenerateStatesNormalizesAndDeduplicatesRequestedStates(t *testing.T) {
	t.Parallel()

	generator := &recordingGenerator{}
	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     t.TempDir(),
		DeviceTokens: []string{"test-token"},
		Generator:    generator,
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	server.mu.Lock()
	session := server.sessions[created.SessionID]
	sourceAsset, err := server.persistUploadedFileLocked(created.SessionID, "source-photos", "portrait.png", "image/png", bytes.NewReader(minimalPNG))
	if err != nil {
		server.mu.Unlock()
		t.Fatalf("persist source asset: %v", err)
	}
	session.SourcePhotos = append(session.SourcePhotos, sourceAsset)
	session.SelectedSourcePhotoID = sourceAsset.ID
	if err := server.persistStoreLocked(); err != nil {
		server.mu.Unlock()
		t.Fatalf("persist session: %v", err)
	}
	server.mu.Unlock()

	statesRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/states:generate",
		`{"states":["idle","working","idle-day","sleeping"]}`,
	)
	if statesRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, statesRecorder.Code, statesRecorder.Body.String())
	}
	statesJobID := statesRecorder.Header().Get("X-MiniMe-Job-ID")
	if statesJobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for state generation")
	}
	if job := waitForJobTerminal(t, server, statesJobID); job.Status != "completed" {
		t.Fatalf("expected completed state job, got %q", job.Status)
	}

	var snapshot remoteSessionSnapshot
	snapshot = fetchSessionSnapshot(t, server, created.SessionID)
	if snapshot.CurrentStepLabel != "idle-day,working,idle-night" {
		t.Fatalf("expected normalized deduplicated states, got %q", snapshot.CurrentStepLabel)
	}
}

func TestQueuedStateJobFailsAfterTimeout(t *testing.T) {
	t.Parallel()

	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     t.TempDir(),
		DeviceTokens: []string{"test-token"},
		Generator:    timeoutGenerator{},
		JobTimeout:   50 * time.Millisecond,
	})
	if err != nil {
		t.Fatalf("create server: %v", err)
	}

	createRecorder := performRequest(t, server.Handler(), http.MethodPost, "/v1/minime/sessions", `{}`)
	var created remoteSessionSnapshot
	decodeJSON(t, createRecorder, &created)

	server.mu.Lock()
	session := server.sessions[created.SessionID]
	sourceAsset, err := server.persistUploadedFileLocked(created.SessionID, "source-photos", "portrait.png", "image/png", bytes.NewReader(minimalPNG))
	if err != nil {
		server.mu.Unlock()
		t.Fatalf("persist source asset: %v", err)
	}
	session.SourcePhotos = append(session.SourcePhotos, sourceAsset)
	session.SelectedSourcePhotoID = sourceAsset.ID
	if err := server.persistStoreLocked(); err != nil {
		server.mu.Unlock()
		t.Fatalf("persist session: %v", err)
	}
	server.mu.Unlock()

	statesRecorder := performRequest(
		t,
		server.Handler(),
		http.MethodPost,
		"/v1/minime/sessions/"+created.SessionID+"/states:generate",
		`{"states":["idle-day"]}`,
	)
	if statesRecorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, statesRecorder.Code, statesRecorder.Body.String())
	}

	jobID := statesRecorder.Header().Get("X-MiniMe-Job-ID")
	if jobID == "" {
		t.Fatal("expected X-MiniMe-Job-ID header for state generation")
	}

	job := waitForJobTerminal(t, server, jobID)
	if job.Status != "failed" {
		t.Fatalf("expected failed state job after timeout, got %q", job.Status)
	}
	if !strings.Contains(job.Error, "exceeded") {
		t.Fatalf("expected timeout error, got %q", job.Error)
	}

	snapshot := fetchSessionSnapshot(t, server, created.SessionID)
	if snapshot.Status != "failed" {
		t.Fatalf("expected failed session status after timeout, got %q", snapshot.Status)
	}
}

func waitForJobTerminal(t *testing.T, server *Server, jobID string) remoteJobSnapshot {
	t.Helper()

	deadline := time.Now().Add(5 * time.Second)
	for time.Now().Before(deadline) {
		jobRecorder := performRequest(t, server.Handler(), http.MethodGet, "/v1/minime/jobs/"+jobID, "")
		if jobRecorder.Code != http.StatusOK {
			t.Fatalf("expected status %d, got %d: %s", http.StatusOK, jobRecorder.Code, jobRecorder.Body.String())
		}

		var job remoteJobSnapshot
		decodeJSON(t, jobRecorder, &job)
		if job.Status == "completed" || job.Status == "failed" {
			return job
		}

		time.Sleep(20 * time.Millisecond)
	}

	t.Fatalf("timed out waiting for job %s to finish", jobID)
	return remoteJobSnapshot{}
}

func waitForJobStatus(t *testing.T, server *Server, jobID string, expectedStatus string) remoteJobSnapshot {
	t.Helper()

	deadline := time.Now().Add(5 * time.Second)
	for time.Now().Before(deadline) {
		jobRecorder := performRequest(t, server.Handler(), http.MethodGet, "/v1/minime/jobs/"+jobID, "")
		if jobRecorder.Code != http.StatusOK {
			t.Fatalf("expected status %d, got %d: %s", http.StatusOK, jobRecorder.Code, jobRecorder.Body.String())
		}

		var job remoteJobSnapshot
		decodeJSON(t, jobRecorder, &job)
		if job.Status == expectedStatus {
			return job
		}

		time.Sleep(20 * time.Millisecond)
	}

	t.Fatalf("timed out waiting for job %s to reach status %q", jobID, expectedStatus)
	return remoteJobSnapshot{}
}

func fetchSessionSnapshot(t *testing.T, server *Server, sessionID string) remoteSessionSnapshot {
	t.Helper()

	recorder := performRequest(t, server.Handler(), http.MethodGet, "/v1/minime/sessions/"+sessionID, "")
	if recorder.Code != http.StatusOK {
		t.Fatalf("expected status %d, got %d: %s", http.StatusOK, recorder.Code, recorder.Body.String())
	}

	var snapshot remoteSessionSnapshot
	decodeJSON(t, recorder, &snapshot)
	return snapshot
}

func uploadSourcePhoto(t *testing.T, server *Server, sessionID, fileName string, contents []byte, contentType string) *httptest.ResponseRecorder {
	t.Helper()

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	partHeader := textproto.MIMEHeader{}
	partHeader.Set("Content-Disposition", fmt.Sprintf(`form-data; name="photos"; filename="%s"`, fileName))
	partHeader.Set("Content-Type", contentType)
	part, err := writer.CreatePart(partHeader)
	if err != nil {
		t.Fatalf("create multipart part: %v", err)
	}
	if _, err := part.Write(contents); err != nil {
		t.Fatalf("write photo contents: %v", err)
	}
	if err := writer.Close(); err != nil {
		t.Fatalf("close multipart writer: %v", err)
	}

	request := httptest.NewRequest(http.MethodPost, "/v1/minime/sessions/"+sessionID+"/photos", body)
	request.Header.Set("Authorization", "Bearer test-token")
	request.Header.Set("Content-Type", writer.FormDataContentType())
	recorder := httptest.NewRecorder()
	server.Handler().ServeHTTP(recorder, request)
	return recorder
}

func newTestServer(t *testing.T) *Server {
	t.Helper()

	server, err := NewServer(Config{
		Port:         "0",
		DataRoot:     t.TempDir(),
		DeviceTokens: []string{"test-token"},
	})
	if err != nil {
		t.Fatalf("create test server: %v", err)
	}
	return server
}

func findRepoRoot(t *testing.T) string {
	t.Helper()

	currentDirectory, err := os.Getwd()
	if err != nil {
		t.Fatalf("get cwd: %v", err)
	}

	directory := currentDirectory
	for {
		if _, err := os.Stat(filepath.Join(directory, "scripts", "bootstrap_main_agent_creation.py")); err == nil {
			return directory
		}
		parent := filepath.Dir(directory)
		if parent == directory {
			t.Fatal("could not locate repo root")
		}
		directory = parent
	}
}

func writeFakeImageGeneratorScript(t *testing.T) string {
	t.Helper()

	scriptPath := filepath.Join(t.TempDir(), "fake_generate_image.py")
	script := fmt.Sprintf(`#!/usr/bin/env python3
import pathlib
import sys

args = sys.argv[1:]
filename = None
prompt = None
for index, arg in enumerate(args):
    if arg == "--filename" and index + 1 < len(args):
        filename = args[index + 1]
    if arg == "--prompt" and index + 1 < len(args):
        prompt = args[index + 1]

if not filename:
    raise SystemExit("missing --filename")

output_path = pathlib.Path(filename)
output_path.parent.mkdir(parents=True, exist_ok=True)
output_path.write_bytes(bytes([%s]))
if prompt is not None:
    output_path.with_suffix(output_path.suffix + ".prompt.txt").write_text(prompt)
print(output_path)
`, bytesLiteral(minimalPNG))
	if err := os.WriteFile(scriptPath, []byte(script), 0o755); err != nil {
		t.Fatalf("write fake image generator script: %v", err)
	}
	return scriptPath
}

func writeFakeStatePipelineScript(t *testing.T) string {
	t.Helper()

	scriptPath := filepath.Join(t.TempDir(), "fake_run_specialist_state_pipeline.py")
	script := `#!/usr/bin/env python3
import pathlib
import sys

args = sys.argv[1:]

def read_arg(name: str) -> str:
    for index, arg in enumerate(args):
        if arg == name and index + 1 < len(args):
            return args[index + 1]
    raise SystemExit(f"missing {name}")

def read_optional_arg(name: str) -> str:
    for index, arg in enumerate(args):
        if arg == name and index + 1 < len(args):
            return args[index + 1]
    return ""

output_root = pathlib.Path(read_arg("--output-root"))
state = read_arg("--state")
prompt_suffix = read_optional_arg("--prompt-suffix")
source_path = output_root / "main-agent" / state / "source.png"
gif_path = output_root / "main-agent" / state / "transparent-frames" / "trimmed-transparent.gif"
source_path.parent.mkdir(parents=True, exist_ok=True)
gif_path.parent.mkdir(parents=True, exist_ok=True)
source_path.write_bytes(b"\x89PNG\r\n\x1a\n")
gif_path.write_bytes(b"GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff!\xf9\x04\x01\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;")
if prompt_suffix:
    (output_root / "main-agent" / state / "prompt_suffix.txt").write_text(prompt_suffix)
print(gif_path)
`
	if err := os.WriteFile(scriptPath, []byte(script), 0o755); err != nil {
		t.Fatalf("write fake state pipeline script: %v", err)
	}
	return scriptPath
}

func bytesLiteral(data []byte) string {
	parts := make([]string, 0, len(data))
	for _, value := range data {
		parts = append(parts, fmt.Sprintf("%d", value))
	}
	return strings.Join(parts, ", ")
}

func performRequest(t *testing.T, handler http.Handler, method, path, body string) *httptest.ResponseRecorder {
	t.Helper()

	request := httptest.NewRequest(method, path, strings.NewReader(body))
	request.Header.Set("Authorization", "Bearer test-token")
	if body != "" {
		request.Header.Set("Content-Type", "application/json")
	}

	recorder := httptest.NewRecorder()
	handler.ServeHTTP(recorder, request)
	return recorder
}

func decodeJSON(t *testing.T, recorder *httptest.ResponseRecorder, target any) {
	t.Helper()

	if err := json.Unmarshal(recorder.Body.Bytes(), target); err != nil {
		t.Fatalf("decode JSON response: %v\nbody: %s", err, recorder.Body.String())
	}
}

var minimalPNG = []byte{
	0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
	0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
	0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
	0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4,
	0x89, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x44, 0x41,
	0x54, 0x78, 0x9c, 0x63, 0xf8, 0xcf, 0xc0, 0x00,
	0x00, 0x03, 0x01, 0x01, 0x00, 0xc9, 0xfe, 0x92,
	0xef, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e,
	0x44, 0xae, 0x42, 0x60, 0x82,
}
